### ISSUE TITLE
Getting base document from translated document

### ISSUE THREAD

**Issue by darenmalfait** [LiamMartens/sanity-plugin-intl-input#63]
**Issue**

Having a document wide translation:
getting a translated page as starting point has no way to get the original document and/or other translated documents

**What I would like**
Having a way to get the related documents from any of the translations, including the base document.

**Possible solution?**
Keeping the document_id without the i18n. part so it can be used to start a new filter.

**Comment by LiamMartens** [comment]
@daren-malfait you can use a `references(i18n.base-id.lang-cult)` -- but as stated in the documentation the translated document structure is based off the base document anyways so you can always just strip out the i18n parts of the id to get the base document id (ref [documentation](https://github.com/LiamMartens/sanity-plugin-intl-input/blob/develop/docs/v4-v5-migration.md#id-structure-change))

eg `'i18n.basedoc-id'.split('.')[1]`

**Comment by fev4** [comment]
I just faced this same question and I was thinking, would it be better (from a querying perspective) to add a ref from the translated doc to the base doc?, this reference can also point to other translations available.

Basically having bidirectional relationships

**Comment by LiamMartens** [comment]
@fev4 I get the idea but I think that would complicate the data structure too much; if you think about relations in databases you generally only have a singular link between 2 objects (one referencing to the other) - but not backwards because that would require a lot more maintenance and updates. I believe with the current data structure it is generally possible to achieve most if not all use cases.
